kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubefledged-controller  
  labels:
    app: kubefledged
    kubefledged: kubefledged-controller  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubefledged-controller
subjects:
- kind: ServiceAccount
  name: kubefledged-controller
  namespace: kube-fledged
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes
