apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefledged-controller
  namespace: kube-fledged
  labels:
    app: kubefledged
    component: kubefledged-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      kubefledged: kubefledged-controller
  template:
    metadata:
      labels:
        kubefledged: kubefledged-controller
        app: kubefledged
    spec:
      initContainers:
        - name: wait
          image: senthilrch/kubefledged-cri-client:v0.8.2
          command: ["curl"]
          args:
            - "--insecure"
            - "--retry-all-errors"
            - "--retry"
            - "60"
            - "--retry-delay"
            - "1"
            - "https://kubefledged-webhook-server.kube-fledged.svc:3443/readyz"
          imagePullPolicy: Always
      containers:
      - image: senthilrch/kubefledged-controller:v0.8.2
        command: ["/opt/bin/kubefledged-controller"]
        args:
        - "--stderrthreshold=INFO"
        - "--image-pull-deadline-duration=5m"
        - "--image-cache-refresh-frequency=15m"
        - "--image-pull-policy=IfNotPresent"
        imagePullPolicy: Always
        name: controller
        env:
        - name: KUBEFLEDGED_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBEFLEDGED_CRI_CLIENT_IMAGE
          value: "senthilrch/kubefledged-cri-client:v0.8.2"
        - name: BUSYBOX_IMAGE
          value: "gcr.io/google-containers/busybox:1.27.2"
      serviceAccountName: kubefledged-controller
