kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubefledged-webhook-server 
  labels:
    app: kubefledged
    kubefledged: kubefledged-webhook-server   
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubefledged-webhook-server
subjects:
- kind: ServiceAccount
  name: kubefledged-webhook-server
  namespace: kube-fledged
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes