apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubefledged-controller
  namespace: kube-fledged
  labels:
    app: kubefledged
    component: kubefledged-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubefledged-webhook-server
  namespace: kube-fledged
  labels:
    app: kubefledged
    component: kubefledged-webhook-server