apiVersion: v1
kind: Service
metadata:
  name: kubefledged-webhook-server
  namespace: kube-fledged
spec:
  ports:
  - name: webhook-server
    port: 3443
    protocol: TCP
    targetPort: 443
  selector:
    kubefledged: kubefledged-webhook-server
  type: ClusterIP
