apiVersion: charts.helm.kubefledged.io/v1alpha2
kind: KubeFledged
metadata:
  name: kube-fledged
  namespace: {{KUBEFLEDGED_NAMESPACE}}
spec:
  # Defaults defined in <project_dir>/helm-charts/kubefledged/values.yaml
  controllerReplicaCount: 1
  webhookServerReplicaCount: 1
  image:
    kubefledgedControllerRepository: docker.io/senthilrch/kubefledged-controller
    kubefledgedCRIClientRepository: docker.io/senthilrch/kubefledged-cri-client
    kubefledgedWebhookServerRepository: docker.io/senthilrch/kubefledged-webhook-server
    pullPolicy: Always
  args:
    controllerLogLevel: INFO
    controllerImagePullDeadlineDuration: 5m
    controllerImageCacheRefreshFrequency: 15m
    controllerImagePullPolicy: IfNotPresent
    webhookServerLogLevel: INFO
    webhookServerCertFile: /var/run/secrets/webhook-server/tls.crt
    webhookServerKeyFile: /var/run/secrets/webhook-server/tls.key
    webhookServerPort: 443
  nameOverride: ""
  fullnameOverride: ""