apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubefledgeds.charts.helm.k8s.io
spec:
  group: charts.helm.k8s.io
  names:
    kind: KubeFledged
    listKind: KubeFledgedList
    plural: kubefledgeds
    singular: kubefledged
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha2
    served: true
    storage: true
