apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubefledged.fullname" . }}-webhook-server
  labels:
    {{- include "kubefledged.labels" . | nindent 4 }}
  namespace: {{ .Values.kubefledgedNameSpace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubefledged.selectorLabels" . | nindent 6 }}-webhook-server
  template:
    metadata:
      labels:
        {{- include "kubefledged.selectorLabels" . | nindent 8 }}-webhook-server
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "kubefledged.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.kubefledgedWebhookServerRepository }}:{{ .Chart.AppVersion }}
          command: {{ .Values.command.kubefledgedWebhookServerCommand }}
          args:
            - "--stderrthreshold={{ .Values.args.webhookServerLogLevel }}"
            - "--cert-file={{ .Values.args.webhookServerCertFile }}"
            - "--key-file={{ .Values.args.webhookServerKeyFile }}"
            - "--port={{ .Values.args.webhookServerPort }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KUBEFLEDGED_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: secret-volume
            mountPath: "/var/run/secrets/webhook-server"
            readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: kubefledged-webhook-server              
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
